#!/usr/bin/env bash -e

rm -rf node_modules dist spec index.html
git checkout origin/master -- dist
git checkout origin/master -- spec
git checkout origin/master -- index.html
rm -rf */*.coffee
npm install

